### ISSUE TITLE
Remove display: block; from .container

### ISSUE THREAD

**Issue by seanwash** [octopuscreative/decent-scss#8]
My reasoning is that mostly you'd use them on divs which are already display block unless directly stated otherwise by css. I also had an issue where I was using flex classes `flex items-center` to center the nav items vertically and `display: block` was overwriting those classes.

http://cl.ly/163A183Z1y2h/Image%202016-03-29%20at%2010.47.43%20AM.png

What do you think @chrsgrffth ?

**Comment by chrsgrffth** [comment]
Do `<section>` and `<article>` tags `display: block` by default? That's the only instance I can think of where `display: block` may be needed. Alternatively, if using a container on one of those tags, you could explicitly call `.d-block`.

**Comment by seanwash** [comment]
In modern browsers I believe they do, the only exception I believe is for IE8, which case you need to include some JS to define that.

I think it'd be better to have to add `.d-block` when you need it then remove it when you don't.

**Comment by chrsgrffth** [comment]
I agree with that.

**Comment by seanwash** [comment]
Alright, I've assigned it to myself so I can take care if it.
